### ISSUE TITLE
Choose License / Copyright

### ISSUE THREAD

**Issue by wdm0006** [anidata/rasp#1]
Palantiri was licensed under the Mozilla license, at the last meeting BSD-3-clause was mentioned as the preferred license, so it was used here.  For this repo and going forward, should we standardize on one? 

Also the copyright attribution I'm guessing should be to Anidata itself, do we have/need a CLA, or are there any discussions to be had there?

**Comment by dlrobertson** [comment]
BSD-3 is good. No need for a CLA IMO... @blakeflei thoughts?

**Comment by wdm0006** [comment]
So can we consider this closed?

**Comment by dlrobertson** [comment]
Yeah, this can be closed.
