### ISSUE TITLE
TorEngine.get_page_source sends a NEWNYM signal to the control port

### ISSUE THREAD

**Issue by dlrobertson** [anidata/rasp#14]
The [TorEngine.get_page_source](https://github.com/anidata/rasp/blob/c9d665165d7d291aa98f565241cd436421de495e/rasp/tor_engine.py#L45-L62) function sends a `NEWNYM` signal to the control port on every call. This is great for our use case where we want our ip to change frequently, but there are many use cases in which it is not so great. This should be configurable. I'd suggest creating a signaler class that can be passed to the `TorEngine` constructor.

```
# Every other GET sends a signal to the control port
eng = TorEngine(..., signaler = rasp.TorController(control_port, signal, 2), ...)
# No signals are sent
eng = TorEngine(..., signaler = None, ...)
```

Maybe this doesn't need to be a separate class, but can be just a number of `GET`s that are run before the signal is sent again.

**Comment by hank-bond** [comment]
Signaling after `n` iterations/gets is probably the simplest implementation of this issue.
We could also signal after `n` seconds elapse, I think that might be a slightly more appropriate move since afaik rate limiters use time as the delimiting factor.

What exactly is the motivation for signaling for a new endpoint?  Do we think we're getting rate limited by certain sites?  Are we trying to pretend we're part of regular traffic so as to avoid detection at all?

**Comment by dlrobertson** [comment]
> We could also signal after n seconds elapse

You bring up a good point here. This makes me disagree with the following comment I made in the PR.

> Maybe this doesn't need to be a separate class, but can be just a number of GETs that are run before the signal is sent again.

I think there will be times when we want to send the signal after n requests and times when we may want it to be timed. We could get real complex and send the signal only if `n` requests have been made in `x` time. So this makes me think we need a configurable class.

> What exactly is the motivation for signaling for a new endpoint? Do we think we're getting rate limited by certain sites? Are we trying to pretend we're part of regular traffic so as to avoid detection at all?

All of the above 😄 . I was getting blocked in our anti-HT project and used this to avoid being blocked.

**Comment by wdm0006** [comment]
It may be as simple as allowing a pre-request callback, which could be anything, but in this case would be sending the signal.  User could mod `time.time()` and end up with a signal every N seconds, or maintain an instance variable counter for every N requests, which wouldn't necessarily play nice with the functional representation, but would be fine as-is.  The same mechanism would also work for the now-deprecated `TimedWait` selenium engine.

**Comment by hank-bond** [comment]
We could modify the N requests attribute at class level across multiple instances of the engine.  Not saying that's a great way to do it, but it is a way to do it.

**Comment by hank-bond** [comment]
Assigned to @baronvonbadguy

**Comment by hank-bond** [comment]
@danlrobertson  Looking into the tor controller source code, and there appears to be a minimum of 10 seconds before an actual NEWNYM signal is accepted by the tor server.

I think we should completely separate the `TorEngine` and `TorController` class. There's just no good way to mix the engine being functional (and threaded) and the TorController class (which will be copied) being in charge of an open connection resource.  We only ever need one of these objects to exist.

I also think we should have the user manage when to send the signal through the controller.  I don't see a benefit in having the user embed the functionality in the `TorController` class.

**Comment by wdm0006** [comment]
I think at the end of the day, once an engine is instantiated, whether it be a TorEngine, SeleniumEngine or DefaultEngine, it should look pretty much the same and be able to be used interchangeably.   So if there is some configuration/state that needs to be maintained to make a TorEngine _just work_, then that should happen at instantiation, not at `get_page_source` time.

**Comment by hank-bond** [comment]
So if we load the function into 10 green threads, will they bind the same `TorController` instance?  Which one closes the connection?  

This whole thing is stupid simple until we decide we want an open connection (volatile resource) to be inside a semi-functional "stateless" object.

**Comment by wdm0006** [comment]
One approach for actual parallelism in an engine (which I haven't experimented with yet), would be to set up the configuration information at instantiation, but in the `get_page_source` catch an exception raised by not having a connection yet, and set up the connection at that time.   That way the `as_func` thing still works, each one having its own curried instance, but you have to rely on the os to clean up your connections. 

Alternatively, we can give each worker a deep copy and they can each use the context manager interface. 

Regardless I'd say that the assumption ought to be that `workers` in the crawlers each have their own instance of an engine, whether that is a semi-functional thingy or a class, tbd.  Either way, the goal should be that the crawlers just get passed in an object (function or class) and treat it the same no matter what.  The differences between them should be upstream, at engine instantiation/configuration if at all possible, not at runtime.

**Comment by hank-bond** [comment]
Say we wanted to go with the "n requests in x seconds".  Is that n requests across all workers?  How are we keeping track of all the requests between each worker?
